# Generated by Django 4.1 on 2022-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_profile_customuser_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
